#!/bin/bash
# ---------- Kakadu Script ----------
# This script is used to repeat the kakadu compress command with
# different rates. At the moment the script covers the rates between
# 0.05 to 2. It also uses three different parameters resulting in
# 120 images and 120 text files.
#
# Instructions:
# 1. Create a new directory for binary executables (this is for ubuntu).
#   $ mkdir ~/bin
#
# 2. copy this file into the bin directory
#
# 3. Change the permissions of the binary file to allow execution.
#   $ chmod 755 ~/bin/kakadu_script-1
#
# 3. Logout from the system
#   $ logout
#
# 4. Create the following directory tree
#   lab1            (main directory)
#	|   n5_RGB.ppm  (main image to compress)
#   |---img         (subdirectory for resulting images)
#   |---logs        (subdirectory for resulting logs)
#
# 5. Navigate to the lab1 directory
#	$ cd /path_to_directory/lab1	(depends on the user)
#
# 6. Execute the binary and enjoy
#	$ kakadu_script-1
#
# TO DO: ask the user the value in which to perform the steps.
#
#	---------- License ---------- 
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Define the parameters
step="0.1"
range_min=0
range_max=5
main_img_size=$(stat -c%s "./n5_GRAY.pgm")

# Calculate de number of samples
samples=$(echo "scale=2; ($range_max-$range_min)/$step;"|bc);

echo ' ,PSNR' > results-2a.csv
echo 'Rate,Real Rate 1,Real Rate 2,Lossy,Real Rate 1,Real Rate 2,PLTL' \
  >> results-2a.csv

for i in `seq 1 $samples`;
do
  rate=$(echo "scale=2; $i*$step+$range_min;"|bc);
  
  # ----- Lossy ------ #
  # Compression
  kdu_compress -i ./n5_GRAY.pgm -o ./img/img_lossy-$i.jp2 -rate $rate Creversible=no

  # Decompression
  kdu_expand -i ./img/img_lossy-$i.jp2 -o ./img/img_lossy-$i.pgm
  
  # Calculate the real rate with the filesize
  # filesize*8/resolution (*8 because we want in bits not bytes)
  lossy_filesize=$(stat -c%s "./img/img_lossy-$i.jp2")
  lossy_real_rate1=$(echo "scale=8; $lossy_filesize*8/5242880;"|bc);
  lossy_real_rate2=$(echo "scale=8; $lossy_filesize*8/$main_img_size;"|bc);

  # Comparison
  psnr_lossy=$(Gcomp -i1 ./n5_GRAY.pgm -i2 ./img/img_lossy-$i.pgm -m 7 -f 1)
  # ------------------ #
  
  # ----- PLTL ------- #
  # Compression
  kdu_compress -i ./n5_GRAY.pgm -o ./img/img_PLTL-$i.jp2 -rate $rate Creversible=yes

  # Decompression
  kdu_expand -i ./img/img_PLTL-$i.jp2 -o ./img/img_PLTL-$i.pgm
  
  
  # Calculate the real rate with the filesize
  # filesize*8/resolution (*8 because we want in bits not bytes)
  pltl_filesize=$(stat -c%s "./img/img_PLTL-$i.jp2")
  pltl_real_rate1=$(echo "scale=8; $pltl_filesize*8/5242880;"|bc);
  pltl_real_rate2=$(echo "scale=8; $pltl_filesize*8/$main_img_size;"|bc);

  # Comparison
  psnr_pltl=$(Gcomp -i1 ./n5_GRAY.pgm -i2 ./img/img_PLTL-$i.pgm -m 7 -f 1)  
  # ------------------ #

  # Saving the values in a spreadsheet
  echo $rate','$lossy_real_rate1','$lossy_real_rate2','$psnr_lossy','\
    $pltl_real_rate1','$pltl_real_rate2','$psnr_pltl >> results-2a.csv

  # Delete the images (cleaning)
  rm ./img/img_PLTL-$i.jp2
  rm ./img/img_PLTL-$i.pgm
  rm ./img/img_lossy-$i.jp2
  rm ./img/img_lossy-$i.pgm
done

echo "*************************"
echo "* Done! Script complete *"
echo "*************************"
